tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','slept')),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','hit'),n('NP',n('NNP','Bill'))),n('.','.'))).
tree(n('NP',n('NP',n('NNP','John'),n('NNP','slept'),n('NNP','Bill')),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','hit')),n('.','.'))).
tree(n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('NN','everyone'))),n('.','.'))).
tree(n('S',n('NP',n('NN','Someone')),n('VP',n('VBZ','likes'),n('NP',n('NN','everyone'))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','does'),n('NP',n('JJ','mary'),n('JJ','like'),n('NN','john'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('WP','Who')),n('SBAR',n('WHNP',n('WDT','that')),n('S',n('VP',n('VBP','john'))))),n('VP',n('VBZ','knows'),n('SQ',n('VBZ','does'),n('NP',n('PRP','he')),n('VP',n('VB','like')))),n('.','.'))).
tree(n('S',n('NP',n('PRP','He')),n('VP',n('VBZ','likes'),n('NP',n('NP',n('NN','everyone')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','john')),n('VP',n('VBZ','knows')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('NP',n('NNP','John')),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','eager'),n('SBAR',n('IN','for'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here')))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','eager'),n('NP',n('NNP','John')),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','eager'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('SBAR',n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADVP',n('RB','here')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('ADVP',n('RB','sincerely')),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('ADVP',n('RB','sincerely')),n('VBP','believe'),n('NP',n('NNP','John'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('ADVP',n('RB','sincerely')),n('NP',n('NNP','John'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','wanted'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','leave'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','persuaded'),n('NP',n('NNP','John')),n('S',n('VP',n('TO','to'),n('VP',n('VB','leave'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','wanted'),n('S',n('NP',n('PRP','it')),n('VP',n('TO','to'),n('VP',n('VB','rain'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','persuaded'),n('NP',n('PRP','it')),n('S',n('VP',n('TO','to'),n('VP',n('VB','rain'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','wanted'),n('S',n('NP',n('DT','the'),n('NN','bus')),n('VP',n('TO','to'),n('VP',n('VB','arrive'),n('PP',n('IN','on'),n('NP',n('NN','time'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','persuaded'),n('NP',n('DT','the'),n('NN','bus')),n('S',n('VP',n('TO','to'),n('VP',n('VB','arrive'),n('PP',n('IN','on'),n('NP',n('NN','time'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','persuaded'),n('NP',n('NNP','John')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','he')),n('VP',n('MD','should'),n('VP',n('VB','leave')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','leave'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','leave'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('NP',n('PRP','it')),n('VP',n('TO','to'),n('VP',n('VB','leave'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('NP',n('DT','the'),n('NN','bus')),n('VP',n('TO','to'),n('VP',n('VB','leave'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADVP',n('RB','here')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('NP',n('DT','a'),n('JJ','pathological'),n('NN','liar')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','want'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','persuaded'),n('S',n('VP',n('TO','to'),n('VP',n('VB','leave')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','believed'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','wanted'),n('S',n('VP',n('TO','to'),n('VP',n('VB','leave')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','park'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','illegal'),n('PP',n('TO','to'),n('NP',n('NN','park')))),n('ADVP',n('RB','here'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('SBAR',n('IN','for'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','park'),n('ADVP',n('RB','here')))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','illegal')),n('SBAR',n('IN','for'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','park'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('SBAR',n('IN','for'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('VP',n('VBN','believed'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','want'),n('SBAR',n('IN','for'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('VP',n('VBN','wanted'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('MD','will'),n('VP',n('VB','win'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('NP',n('NNP','John')),n('S',n('VP',n('TO','to'),n('VP',n('VB','win')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','arrested'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBN','arrested')),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBD','was'),n('VP',n('VBN','arrested'),n('NP',n('NNP','John')))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBN','arrested'),n('NP',n('NNP','John'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBN','arrested'),n('NP',n('NNP','John'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','arrested'),n('PP',n('IN','by'),n('NP',n('DT','the'),n('NN','police'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','intelligent')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBD','was'),n('VP',n('VBN','believed'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','intelligent'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','believed'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','intelligent'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('VP',n('VBN','believed'),n('PP',n('IN','by'),n('NP',n('NN','everyone'))),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','intelligent'))))))),n('.','.'))).
tree(n('S',n('SBAR',n('IN','That'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','intelligent'))))),n('VP',n('VBZ','is'),n('VP',n('VBN','believed'),n('PP',n('IN','by'),n('NP',n('NN','everyone'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','proud'),n('NP',n('NNP','John')))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','proud'),n('PP',n('IN','of'),n('NP',n('NNP','John'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','proud'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('PRP','you')),n('VP',n('MD','will'),n('VP',n('VB','see')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('MD','will'),n('VP',n('VB','see'),n('WP','who')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','Bill')),n('VP',n('VBZ','wonders'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBD','saw'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','Bill')),n('VP',n('VBZ','wonders'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBD','saw'),n('NP',n('WP','what')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','What')),n('SQ',n('VBZ','does'),n('NP',n('NNP','Bill')),n('VP',n('VB','wonder'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBD','saw')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','mention'),n('NP',n('NP',n('NP',n('NNP','Bill'),n('POS','\'s')),n('NN','belief')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','you')),n('VP',n('VBD','saw'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','mention'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','Bill')),n('VP',n('VBZ','believes'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','you')),n('VP',n('VBD','saw'))))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('VBP','think'),n('SBAR',n('S',n('NP',n('NNP','John')),n('VP',n('VBD','said'),n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('MD','will'),n('VP',n('VB','see'),n('WP','who')))))))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('VBP','think'),n('SBAR',n('S',n('NP',n('NNP','John')),n('VP',n('VBD','said'))))))),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('PRP','you')),n('VP',n('MD','will'),n('VP',n('VB','see'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('VBP','think'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','said'),n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('MD','will'),n('VP',n('VB','see')))))))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('PRP','you')),n('VP',n('VBP','think'),n('SBAR',n('S',n('NP',n('NNP','John')),n('VP',n('VBD','said'),n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('MD','will'),n('VP',n('VB','see')))))))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','Bill')),n('VP',n('VBZ','wonders'),n('NP',n('NP',n('WP','what')),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBD','saw')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','Bill')),n('VP',n('MD','will'),n('VP',n('VB','solve'),n('NP',n('WDT','which'),n('NN','problem')))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WDT','Which'),n('NN','problem')),n('SQ',n('MD','will'),n('NP',n('NNP','Bill')),n('VP',n('VB','solve'))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','problem')),n('VP',n('VBD','was'),n('VP',n('VBN','solved'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('VP',n('VBG','raining'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('VP',n('VBG','raining'))))))),n('.','.'))).
tree(n('SQ',n('VBZ','Is'),n('NP',n('NN','raining')),n('.','.'))).
tree(n('SQ',n('VP',n('VBZ','Is'),n('ADJP',n('JJ','likely'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('VP',n('VBG','raining')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','likely'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADVP',n('RB','here')))))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('PRP','him'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('PRP','himself'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('PRP','him')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('PRP','himself')))))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','mother')),n('VP',n('VBZ','likes'),n('NP',n('PRP','himself'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','picture')),n('PP',n('IN','of'),n('NP',n('PRP','himself')))),n('VP',n('VBZ','is'),n('ADJP',n('JJ','nice'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','mother')),n('VP',n('VBZ','likes'),n('NP',n('PRP','him'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','picture')),n('PP',n('IN','of'),n('NP',n('PRP','him')))),n('VP',n('VBZ','is'),n('ADJP',n('JJ','nice'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','Himself')),n('VP',n('VBZ','likes'),n('NP',n('NNP','John'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','like'),n('NP',n('DT','each'),n('JJ','other'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('PRP$','Their'),n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('DT','each'),n('JJ','other')))),n('VP',n('VBP','are'),n('ADJP',n('JJ','nice'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','believe'),n('SBAR',n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('DT','each'),n('JJ','other')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP$','Their'),n('NNS','mothers')),n('VP',n('VBP','like'),n('NP',n('DT','each'),n('JJ','other'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','Each')),n('ADJP',n('JJ','other'))),n('VP',n('VBP','like'),n('NP',n('PRP','them'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('S',n('NP',n('PRP','himself')),n('VP',n('TO','to'),n('VP',n('VB','like'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('S',n('NP',n('PRP','him')),n('VP',n('TO','to'),n('VP',n('VB','like'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','himself')),n('VP',n('VBZ','likes'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','he')),n('VP',n('VBZ','likes'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('S',n('NP',n('NNP','Mary')),n('VP',n('TO','to'),n('VP',n('VB','like'),n('NP',n('PRP','himself')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('S',n('NP',n('NNP','Mary')),n('VP',n('TO','to'),n('VP',n('VB','like'),n('NP',n('PRP','him')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('NP',n('NP',n('NNP','Mary'),n('POS','\'s')),n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('PRP','him'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('NP',n('NP',n('NNP','Mary'),n('POS','\'s')),n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('PRP','himself'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('NP',n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('PRP','himself'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','saw'),n('NP',n('NP',n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('PRP','himself'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','saw'),n('NP',n('NP',n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('PRP','him'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','read'),n('NP',n('PRP$','their'),n('NNS','books'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','read'),n('NP',n('NP',n('DT','each'),n('JJ','other'),n('POS','\'s')),n('NNS','books'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','read'),n('NP',n('NP',n('PRP','themselves'),n('POS','\'')),n('NNS','books'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('NNP','John'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('PRP','he')),n('VP',n('VBZ','likes'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('NNP','John')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('PRP','him')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('MD','ca'),n('RB','n\'t'),n('VP',n('VB','stand'),n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','teacher')))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','teacher')),n('VP',n('MD','ca'),n('RB','n\'t'),n('VP',n('VB','stand'),n('NP',n('NNP','John')))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('MD','ca'),n('RB','n\'t'),n('VP',n('VB','stand'),n('NP',n('NP',n('DT','the'),n('NN','bastard'),n('POS','\'s')),n('NN','teacher')))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','teacher')),n('VP',n('MD','ca'),n('RB','n\'t'),n('VP',n('VB','stand'),n('NP',n('DT','the'),n('NN','bastard')))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('DT','the'),n('NN','bastard')),n('VP',n('VBZ','likes'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('DT','the'),n('NN','bastard')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','He')),n('VP',n('VBZ','likes'),n('NP',n('NNP','John'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','He')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('NNP','Mary')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','He')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('NNP','John')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','He')),n('VP',n('MD','ca'),n('RB','n\'t'),n('VP',n('VB','stand'),n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','teacher')))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('PRP','him'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','does'),n('NP',n('PRP','he')),n('VP',n('VB','think'),n('SBAR',n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes')))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','left'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','himself')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','clever')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','believed'),n('SBAR',n('WHNP',n('WDT','that')),n('S',n('VP',n('VBZ','is'),n('ADJP',n('JJ','clever'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','believes'),n('S',n('NP',n('PRP','himself')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','believed'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','He')),n('VP',n('VBZ','likes'),n('NP',n('PRP','him'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','left')),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('PRP','himself'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','We')),n('VP',n('VBP','like'),n('NP',n('PRP','me'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','We')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','I')),n('VP',n('MD','will'),n('VP',n('VB','win')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','We')),n('VP',n('VBP','like'),n('NP',n('PRP','myself'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','like'),n('NP',n('PRP','themselves'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','told'),n('NP',n('NNP','Bill')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','they')),n('VP',n('MD','should'),n('VP',n('VB','leave')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','want'),n('S',n('VP',n('TO','to'),n('VP',n('VB','visit'),n('NP',n('PRP','you')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','want'),n('S',n('VP',n('TO','to'),n('VP',n('VB','visit'),n('NP',n('DT','each'),n('JJ','other')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','understand'),n('NP',n('DT','the'),n('NN','problem')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','important')),n('S',n('VP',n('TO','to'),n('VP',n('VB','understand'),n('NP',n('DT','the'),n('NN','problem')))))),n('.','.'))).
tree(n('NP',n('NP',n('NNS','Eats')),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','important')),n('S',n('VP',n('TO','to'),n('VP',n('VB','eat'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','Was')),n('VP',n('VBN','arrested')),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBD','was'),n('VP',n('VBN','arrested'))),n('.','.'))).
tree(n('S',n('NP',n('EX','There')),n('VP',n('VBD','was'),n('VP',n('VBN','arrested'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADVP',n('RB','here')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','want'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','win'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','want'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','win'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('S',n('NP',n('NNP','John')),n('VP',n('TO','to'),n('VP',n('VB','have'),n('VP',n('VBN','won')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','believe'),n('S',n('VP',n('TO','to'),n('VP',n('VB','have'),n('VP',n('VBN','won')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','saw'),n('NP',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','destruction')),n('PP',n('IN','of'),n('NP',n('DT','the'),n('NN','building'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','saw'),n('S',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','destruction')),n('NP',n('DT','the'),n('NN','building')))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','saw'),n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','destruction'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','proud'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','proud'),n('PP',n('IN','of'),n('NP',n('NP',n('PRP$','my'),n('NN','belief')),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','intelligent'))))))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NNS','men')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('NP',n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('DT','each'),n('JJ','other')))),n('VP',n('MD','will'),n('VP',n('VB','be'),n('PP',n('IN','on'),n('NP',n('NN','sale')))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBD','liked'),n('NP',n('NP',n('NP',n('NNP','Mary'),n('POS','\'s')),n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('DT','each'),n('JJ','other'))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','like'),n('NP',n('NP',n('DT','each'),n('JJ','other'),n('POS','\'s')),n('NNS','books'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('DT','each'),n('JJ','other')),n('VP',n('VBP','are'),n('ADJP',n('JJ','intelligent')))))),n('.','.'))).
tree(n('NP',n('NP',n('DT','Each'),n('ADJP',n('JJ','other'),n('NN','left'))),n('.','.'))).
tree(n('NP',n('NP',n('NNP','Left')),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NNS','men')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('NP',n('NP',n('NNP','Mary'),n('POS','\'s')),n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('DT','each'),n('JJ','other')))),n('VP',n('MD','will'),n('VP',n('VB','be'),n('PP',n('IN','on'),n('NP',n('NN','sale')))))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NNS','men')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','I')),n('VP',n('VBP','like'),n('NP',n('NP',n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('DT','each'),n('JJ','other')))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','it')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('SBAR',n('IN','that'),n('S',n('NP',n('NP',n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('DT','each'),n('JJ','other')))),n('VP',n('VBP','are'),n('PP',n('IN','on'),n('NP',n('NN','sale'))))))))))),n('.','.'))).
tree(n('S',n('SBAR',n('IN','That'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADVP',n('RB','here'))))),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','They')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','it')),n('VP',n('VBD','surprised'),n('NP',n('DT','each'),n('JJ','other')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','Bill')),n('VP',n('VBD','won')))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','leave')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','seems'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','it')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','leave'))))))))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NNPS','Pictures')),n('PP',n('IN','of'),n('NP',n('DT','each'),n('JJ','other')))),n('VP',n('VBP','are'),n('PP',n('IN','on'),n('NP',n('NN','sale')))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NNPS','Pictures')),n('PP',n('IN','of'))),n('VP',n('VBP','are'),n('PP',n('IN','on'),n('NP',n('NN','sale')))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NNS','men')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('NP',n('NNS','pictures')),n('PP',n('IN','of'),n('NP',n('PRP','them')))),n('VP',n('VBP','are'),n('PP',n('IN','on'),n('NP',n('NN','sale'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','said'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP$','his'),n('NN','brother')),n('VP',n('VBZ','likes'),n('NP',n('PRP','himself')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','We')),n('VP',n('VBD','believed'),n('S',n('NP',n('NNP','Mary')),n('VP',n('TO','to'),n('VP',n('VB','like'),n('NP',n('DT','each'),n('JJ','other')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','He')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','likes'),n('NP',n('NNP','John')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','does'),n('NP',n('PRP','he')),n('VP',n('VB','like'))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','was'),n('VP',n('VBN','arrested')))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','seems'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','crazy')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','arrested'),n('PP',n('IN','after'),n('S',n('VP',n('VBG','leading'),n('NP',n('DT','the'),n('NN','demonstration'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('RB','too'),n('JJ','dumb'),n('S',n('VP',n('TO','to'),n('VP',n('VB','talk'),n('PP',n('TO','to'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','he')),n('VP',n('VB','try'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WDT','Which'),n('NN','report')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','file'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','reading')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WDT','Which'),n('NN','book')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','file'),n('NP',n('DT','the'),n('NN','report')),n('PP',n('IN','without'),n('S',n('VP',n('VBG','reading')))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','filed'),n('NP',n('WDT','which'),n('NN','report')),n('PP',n('IN','without'),n('S',n('VP',n('VBG','reading')))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','report')),n('VP',n('VBD','was'),n('VP',n('VBN','filed'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','reading')))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','report')),n('VP',n('VBD','fell'),n('PP',n('IN','on'),n('NP',n('DT','the'),n('NN','floor'))),n('PP',n('IN','after'),n('S',n('VP',n('VBG','reading'),n('NP',n('DT','the'),n('NN','book')))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','teacher')),n('VP',n('VBD','fell'),n('PP',n('IN','on'),n('NP',n('DT','the'),n('NN','floor'))),n('PP',n('IN','after'),n('S',n('VP',n('VBG','reading'),n('NP',n('DT','the'),n('NN','book')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WDT','Which'),n('NN','report')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','file'),n('SBAR',n('IN','after'),n('S',n('NP',n('PRP','you')),n('VP',n('VBP','read')))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','report')),n('VP',n('VBD','was'),n('VP',n('VBN','filed'),n('SBAR',n('IN','after'),n('S',n('NP',n('NNP','Bill')),n('VP',n('VBD','read')))))),n('.','.'))).
tree(n('S',n('NP',n('WP','What')),n('VP',n('VBD','was'),n('VP',n('VBN','filed'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','being'),n('VP',n('VBN','read'))))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','report')),n('VP',n('VBD','was'),n('VP',n('VBN','filed'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','being'),n('VP',n('VBN','read'))))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','report')),n('VP',n('VBD','disappeared'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','being'),n('VP',n('VBN','read')))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','teacher')),n('VP',n('VBD','was'),n('VP',n('VBN','fired'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','talking'),n('PP',n('TO','to'))))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','teacher')),n('VP',n('VBD','was'),n('VP',n('VBN','fired'),n('SBAR',n('IN','after'),n('S',n('NP',n('PRP','he')),n('VP',n('VBD','talked'),n('PP',n('TO','to'))))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','teacher')),n('VP',n('VBD','resigned'),n('PP',n('IN','after'),n('S',n('VP',n('VBG','talking'),n('PP',n('TO','to')))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','resigned'),n('SBAR',n('IN','before'),n('S',n('NP',n('PRP','we')),n('VP',n('MD','could'),n('VP',n('VB','fire'))))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','resigned'),n('SBAR',n('IN','before'),n('S',n('NP',n('PRP','we')),n('VP',n('MD','could'),n('VP',n('VB','fire'),n('NP',n('PRP','him')))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','hire'),n('SBAR',n('IN','because'),n('S',n('NP',n('NNP','Mary')),n('VP',n('VBD','said'),n('SBAR',n('S',n('VP',n('MD','would'),n('VP',n('VB','work'),n('ADVP',n('RB','hard'))))))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','hire'),n('SBAR',n('IN','because'),n('S',n('NP',n('PRP','he')),n('VP',n('VBD','said'),n('SBAR',n('S',n('VP',n('MD','would'),n('VP',n('VB','work'),n('ADVP',n('RB','hard'))))))))))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','report')),n('SBAR',n('WHNP',n('WDT','which')),n('S',n('NP',n('PRP','I')),n('VP',n('VBD','filed'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','reading')))))))),n('VP',n('VBD','disappeared')),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','man')),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('PRP','I')),n('VP',n('VBD','hired'),n('SBAR',n('RB','because'),n('S',n('NP',n('NNP','Mary')),n('VP',n('VBD','said'),n('SBAR',n('S',n('VP',n('MD','would'),n('VP',n('VB','work'),n('ADVP',n('RB','hard'))))))))))))),n('VP',n('VBD','disappeared')),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','man')),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('PRP','I')),n('VP',n('VBD','hired'),n('SBAR',n('RB','because'),n('S',n('NP',n('PRP','he')),n('VP',n('VBD','said'),n('SBAR',n('S',n('VP',n('MD','would'),n('VP',n('VB','work'),n('ADVP',n('RB','hard'))))))))))))),n('VP',n('VBD','disappeared')),n('.','.'))).
tree(n('S',n('NP',n('DT','This'),n('NN','article')),n('VP',n('VBZ','is'),n('ADJP',n('RB','too'),n('JJ','illogical'),n('S',n('VP',n('TO','to'),n('VP',n('VB','read'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','laughing'),n('PP',n('IN','at')))))))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','left'),n('SBAR',n('IN','after'),n('S',n('NP',n('PRP','you')),n('VP',n('VBD','insulted')))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','left'),n('SBAR',n('IN','after'),n('S',n('NP',n('PRP','you')),n('VP',n('VBD','insulted'),n('NP',n('PRP','him'))))))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','article')),n('SBAR',n('WHNP',n('WDT','which')),n('S',n('NP',n('PRP','I')),n('VP',n('VBD','filed'),n('NP',n('PRP','it')),n('NP',n('NN','yesterday')),n('PP',n('IN','without'),n('S',n('VP',n('VBG','reading')))))))),n('VP',n('VBZ','is'),n('ADVP',n('IN','over'),n('RB','here'))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','What')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','meet'),n('NP',n('NP',n('DT','a'),n('NN','man')),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBZ','likes'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','give'),n('NP',n('NP',n('DT','a'),n('NN','picture')),n('PP',n('IN','of'))),n('PP',n('TO','to')))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','give'),n('NP',n('NP',n('DT','a'),n('NN','picture')),n('PP',n('IN','of'))),n('PP',n('TO','to'),n('NP',n('NNP','Bill'))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','give'),n('NP',n('NP',n('DT','a'),n('NN','picture')),n('PP',n('IN','of'),n('NP',n('NNP','Bill')))),n('PP',n('TO','to')))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','give'),n('NP',n('NP',n('DT','a'),n('NN','picture')),n('WHPP',n('IN','of'),n('WHNP',n('WP','who')))),n('PP',n('TO','to')))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','put'),n('NP',n('NP',n('DT','a'),n('NN','picture')),n('PP',n('IN','of'),n('NP',n('IN','under')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','hired'))),n('.','.'))).
tree(n('NP',n('NP',n('NNP','Died')),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','was'),n('VP',n('VBN','killed'))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','was'),n('VP',n('VBN','killed')))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','wanted'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('VP',n('VBN','arrested')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','is'),n('NP',n('PRP','it')),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VP',n('VBZ','is'),n('SBAR',n('S',n('NP',n('PRP','it')),n('ADVP',n('RB','likely')),n('VP',n('MD','will'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race')))))))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','man')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('IN','whether'),n('S',n('NP',n('PRP','he')),n('VP',n('MD','will'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race')))))))))),n('VP',n('VBD','disappeared')),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','man')),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('IN','whether'),n('S',n('NP',n('PRP','he')),n('VP',n('MD','will'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race')))))))))),n('VP',n('VBD','disappeared')),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','man')),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('PRP','you')),n('VP',n('VBP','wonder'),n('SBAR',n('IN','whether'),n('S',n('NP',n('PRP','he')),n('VP',n('MD','will'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race')))))))))),n('VP',n('VBD','disappeared')),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WDT','Which'),n('NN','man')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','wonder'),n('SBAR',n('IN','whether'),n('S',n('NP',n('PRP','he')),n('VP',n('MD','will'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race')))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('NP',n('NP',n('JJ','crucial'),n('NN','john')),n('S',n('VP',n('TO','to'),n('VP',n('VB','see'),n('NP',n('DT','this'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','crucial'),n('S',n('VP',n('TO','to'),n('VP',n('VB','see'),n('NP',n('DT','this'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','certain'),n('S',n('VP',n('TO','to'),n('VP',n('VB','see'),n('NP',n('DT','this'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','certain'),n('S',n('VP',n('TO','to'),n('VP',n('VB','see'),n('NP',n('DT','this'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','saw')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','think'),n('SBAR',n('S',n('NP',n('NNP','John')),n('VP',n('VBD','saw')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','think'),n('SBAR',n('WHNP',n('WDT','that')),n('S',n('VP',n('VBD','saw'),n('NP',n('NNP','Bill'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','think'),n('SBAR',n('S',n('VP',n('VBD','saw'),n('NP',n('NNP','Bill'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','say'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('VP',n('VBN','believed'),n('SBAR',n('S',n('VP',n('VBZ','is'),n('ADJP',n('JJ','intelligent'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','seems'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','it')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','leave'))))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('MD','will'),n('VP',n('VB','read'),n('FRAG',n('WHNP',n('WP','what'))))),n('.','.'))).
tree(n('NP',n('NP',n('WP','What'),n('NN','will')),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBP','read')))),n('.','.'))).
tree(n('S',n('NP',n('PRP','You')),n('VP',n('MD','will'),n('VP',n('VB','read'),n('FRAG',n('WHNP',n('WP','what'))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','What')),n('SQ',n('MD','will'),n('NP',n('PRP','you')),n('VP',n('VB','read'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('MD','will'),n('VP',n('VB','read'),n('FRAG',n('WHNP',n('WP','what')))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('S',n('NP',n('PRP','you')),n('VP',n('MD','will'),n('VP',n('VB','read'),n('NP',n('DT','the'),n('NN','book'))))))),n('.','.'))).
tree(n('SBARQ',n('WHADVP',n('WRB','Why')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','read'),n('FRAG',n('WHNP',n('WP','what'))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','What')),n('SQ',n('VBD','did'),n('NP',n('PRP','you')),n('VP',n('VB','read'),n('FRAG',n('WHADVP',n('WRB','why'))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBD','left'),n('SBAR',n('WHADVP',n('WRB','why'))))),n('.','.'))).
tree(n('SBARQ',n('WHADVP',n('WRB','Why')),n('SQ',n('VP',n('VBD','did'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBP','leave')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','believes'),n('NP',n('NP',n('DT','the'),n('NN','claim')),n('SBAR',n('WHADVP',n('IN','that')),n('S',n('NP',n('NNP','Mary')),n('VP',n('VBD','read'),n('NP',n('WP','what'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','What')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','believe'),n('NP',n('NP',n('DT','the'),n('NN','claim')),n('SBAR',n('WHADVP',n('IN','that')),n('S',n('NP',n('NNP','Mary')),n('VP',n('VBD','read'))))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WP','Who')),n('S',n('VP',n('VBZ','believes'),n('NP',n('NP',n('DT','the'),n('NN','claim')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','hit'),n('WP','who'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','believes'),n('NP',n('NP',n('DT','the'),n('NN','claim')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','left'),n('SBAR',n('WHADVP',n('WRB','why')))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','does'),n('NP',n('NNP','Mary')),n('VP',n('VB','believe'),n('NP',n('NP',n('DT','the'),n('NN','claim')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','hit'))))))),n('.','.'))).
tree(n('SBARQ',n('WHADVP',n('WRB','Why')),n('SQ',n('VBZ','does'),n('NP',n('NNP','Mary')),n('VP',n('VB','believe'),n('NP',n('NP',n('DT','the'),n('NN','claim')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','left'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','does'),n('NP',n('NNP','Mary')),n('VP',n('VB','wonder'),n('SBAR',n('WHADVP',n('WRB','why')),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','hit')))))),n('.','.'))).
tree(n('SBARQ',n('WHADVP',n('WRB','Why')),n('SQ',n('VBZ','does'),n('NP',n('NNP','Mary')),n('VP',n('VB','wonder'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','hit')))))),n('.','.'))).
tree(n('SBARQ',n('WHADVP',n('WRB','Why')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','left')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','think'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','Mary')),n('VP',n('VBD','said'),n('VP',n('VBN','won'),n('NP',n('DT','the'),n('NN','race')))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBP','do'),n('NP',n('PRP','you')),n('VP',n('VB','think'),n('SBAR',n('WHNP',n('WDT','that')),n('S',n('VP',n('VBD','left')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('NP',n('NNP','John')),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','Mary')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','Mary')),n('VP',n('VBD','tried'),n('S',n('NP',n('NNP','Bill')),n('VP',n('TO','to'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race')))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','is'),n('NP',n('PRP','it')),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever'))))))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','man')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','it')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever')))))))))),n('VP',n('VBD','disappeared')),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','man')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','it')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely')))))),n('VP',n('VBZ','is'),n('ADJP',n('JJ','clever')),n('ADJP',n('VBN','disappeared'))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('NP',n('PRP','it')),n('VP',n('TO','to'),n('VP',n('VB','rain')))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('ADVP',n('RB','there')),n('VP',n('TO','to'),n('VP',n('VB','be'),n('NP',n('DT','a'),n('NN','man')),n('ADVP',n('RB','here'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBD','tried'),n('S',n('NP',n('PRP','it')),n('VP',n('TO','to'),n('VP',n('VB','seem'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','Bill')),n('VP',n('VBD','was'),n('ADJP',n('JJ','intelligent'))))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('NP',n('PRP','it')),n('VP',n('TO','to'),n('VP',n('VB','seem'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','Bill')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','intelligent')))))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('ADVP',n('RB','often')),n('VP',n('VBZ','rains'),n('PP',n('IN','without'),n('S',n('VP',n('VBG','snowing'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','intelligent'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','I')),n('VP',n('VBP','am'),n('ADJP',n('JJ','proud'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','won'),n('NP',n('DT','the'),n('NN','race'))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','tough'),n('SBAR',n('S',n('VP',n('TO','to'),n('VP',n('VB','please'))))))),n('.','.'))).
tree(n('S',n('NP',n('PRP','It')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','tough'),n('SBAR',n('S',n('VP',n('TO','to'),n('VP',n('VB','please'),n('NP',n('NNP','John')))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','likely'),n('S',n('VP',n('TO','to'),n('VP',n('VB','win'),n('NP',n('DT','the'),n('NN','race'))))))),n('.','.'))).
tree(n('SBARQ',n('WHNP',n('WP','Who')),n('SQ',n('VBZ','does'),n('NP',n('PRP$','his'),n('NN','mother')),n('VP',n('VB','love'))),n('.','.'))).
tree(n('S',n('NP',n('PRP$','His'),n('NN','mother')),n('VP',n('VBZ','loves'),n('NP',n('NN','everyone'))),n('.','.'))).
tree(n('S',n('NP',n('DT','Every'),n('NN','man')),n('VP',n('VBZ','likes'),n('NP',n('NP',n('DT','some'),n('NN','symphony')),n('SBAR',n('S',n('NP',n('PRP','he')),n('VP',n('VBD','heard')))))),n('.','.'))).
tree(n('S',n('NP',n('DT','Every'),n('NN','man')),n('VP',n('VBD','asked'),n('NP',n('DT','some'),n('NN','actress')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','he')),n('VP',n('VBD','met'),n('PP',n('IN','about'),n('NP',n('NP',n('DT','some'),n('NN','play')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','she')),n('VP',n('VBD','appeared'),n('PRT',n('RP','in'))))))))))),n('.','.'))).
tree(n('S',n('NP',n('NN','Someone')),n('VP',n('VBD','gave'),n('NP',n('NP',n('DT','every'),n('NN','actress')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','he')),n('VP',n('VBD','met'),n('NP',n('NP',n('DT','a'),n('NN','book')),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','she')),n('VP',n('VBD','appreciated')))))))))),n('.','.'))).
tree(n('SBAR',n('WHNP',n('WDT','Which'),n('NN','man')),n('S',n('VP',n('VBD','liked'),n('SBAR',n('WHNP',n('WDT','which')),n('S',n('VP',n('VBP','symphony'),n('SBAR',n('S',n('NP',n('PRP','he')),n('VP',n('VBD','heard'))))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','seems'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','he')),n('VP',n('VBZ','likes'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','asked'),n('NP',n('NNP','Mary')),n('PP',n('IN','about'),n('NP',n('PRP','themselves')))),n('.','.'))).
tree(n('S',n('NP',n('PRP','We')),n('VP',n('VBP','like'),n('NP',n('PRP','myself'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','seems'),n('SBAR',n('S',n('VP',n('VBZ','is'),n('ADJP',n('JJ','crazy')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','tried'),n('S',n('NP',n('NNP','Bill')),n('VP',n('TO','to'),n('VP',n('VB','seem'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','he')),n('VP',n('VBZ','likes')))))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBD','tried'),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('VP',n('VBN','arrested')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','Mary')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','proud'),n('PP',n('IN','of'),n('NP',n('NNP','Bill'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','seems'),n('SBAR',n('IN','that'),n('S',n('NP',n('PRP','he')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','proud')))))),n('.','.'))).
tree(n('S',n('NP',n('DT','The'),n('NN','destruction'),n('NNP','Rome')),n('VP',n('VBD','worked')),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','destruction')),n('PP',n('IN','of'),n('NP',n('NNP','Rome')))),n('VP',n('VBD','worked')),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','belief')),n('NP',n('NNP','John')),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever')))))),n('VP',n('VBZ','is'),n('ADJP',n('JJ','illogical'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','belief')),n('PP',n('IN','of'),n('NP',n('NNP','John'))),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever')))))),n('VP',n('VBZ','is'),n('ADJP',n('JJ','illogical'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','The'),n('NN','belief')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','is'),n('ADJP',n('JJ','clever')))))),n('VP',n('VBZ','is'),n('ADJP',n('JJ','illogical'))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NP',n('NNP','John'),n('POS','\'s')),n('NN','belief')),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever')))))),n('VP',n('VBZ','is'),n('ADJP',n('JJ','illogical'))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','seems'),n('SBAR',n('IN','that'),n('S',n('NP',n('NP',n('PRP$','his'),n('NN','belief')),n('S',n('VP',n('TO','to'),n('VP',n('VB','be'),n('ADJP',n('JJ','clever')))))),n('VP',n('VBZ','is'),n('ADJP',n('RB','ill'),n('VBN','founded')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n(',',','),n('NP',n('PRP','I')),n('VP',n('VBP','like')),n('.','.'))).
tree(n('S',n('NP',n('NNP','John'),n(',',','),n('NNP','Mary')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('PRP','I')),n('VP',n('VBP','like'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n(',',','),n('NP',n('PRP','he')),n('VP',n('VBZ','thinks'),n('SBAR',n('S',n('NP',n('PRP','I')),n('VP',n('VBP','like'))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John'),n(',',','),n('NNP','Mary')),n('VP',n('VBZ','thinks'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBD','said'),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','Susan')),n('VP',n('VBZ','believes'),n('SBAR',n('S',n('NP',n('PRP','I')),n('VP',n('VBP','like'))))))))))),n('.','.'))).
tree(n('S',n('NP',n('JJ','Syntactic'),n('NNS','structures')),n(',',','),n('NP',n('PRP','I')),n('VP',n('VBP','wonder'),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBP','read'))))),n('.','.'))).
tree(n('S',n('NP',n('JJ','Syntactic'),n('NNS','structures')),n(',',','),n('NP',n('PRP','I')),n('VP',n('VBD','met'),n('NP',n('NP',n('DT','the'),n('NN','man')),n('SBAR',n('WHNP',n('WP','who')),n('S',n('VP',n('VBD','wrote')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n(',',','),n('NP',n('PRP','I')),n('VP',n('VBP','think'),n('SBAR',n('IN','that'),n('S',n('VP',n('VBN','won'),n('NP',n('DT','the'),n('NN','race')))))),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n(',',','),n('NP',n('PRP','I')),n('VP',n('VBP','think'),n('VP',n('VBN','won'),n('NP',n('DT','the'),n('NN','race')))),n('.','.'))).
tree(n('S',n('NP',n('PRP','He')),n('VP',n('VBZ','likes'),n('NP',n('NP',n('NN','everyone')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','knows')))))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('NN','Everyone')),n('SBAR',n('IN','that'),n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','knows'),n('NP',n('PRP','he')))))),n('VP',n('VBZ','likes')),n('.','.'))).
tree(n('S',n('NP',n('NNP','John')),n('VP',n('VBZ','likes'),n('NP',n('NP',n('DT','every'),n('NN','picture')),n('PP',n('IN','of'),n('NP',n('PRP','himself'))))),n('.','.'))).
tree(n('S',n('NP',n('NP',n('DT','Every'),n('NN','picture')),n('PP',n('IN','of'),n('NP',n('PRP','himself'))),n('NP',n('NNP','John'))),n('VP',n('VBZ','likes')),n('.','.'))).