((John (NNP)) (slept (NN)))  
((John (NNP)) (hit (NNP)) (Bill (NNP)))  
((John (NNP)) (slept (NNP)) (Bill (NNP)))  
((John (NNP)) (hit (NNP)))  
((Mary (NNP)) (likes (VBZ)) (everyone (NN)))  
((Someone (NN)) (likes (NNS)) (everyone (NN)))  
((Who (NNP)) (does (VBZ)) (mary (JJ)) (like (IN)) (john (NN)))  
((Who (NNP)) (that (WDT)) (john (VBP)) (knows (VBZ)) (does (VBZ)) (he (PRP)) (like (VB)))  
((He (PRP)) (likes (VBZ)) (everyone (NN)) (that (IN)) (john (NNP)) (knows (VBZ)))  
((John (NNP)) (is (VBZ)) (likely (JJ)) (to (TO)) (be (VB)) (here (RB)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (that (IN)) (John (NNP)) (is (VBZ)) (here (RB)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (John (NNP)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (am (VBP)) (eager (JJR)) (for (IN)) (John (NNP)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (am (VBP)) (eager (JJR)) (John (NNP)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (am (VBP)) (eager (JJR)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (believe (VBP)) (John (NNP)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (believe (VBP)) (John (NNP)) (is (VBZ)) (here (RB)))  
((I (PRP)) (believe (VBP)) (sincerely (RB)) (John (NNP)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (sincerely (RB)) (believe (VBP)) (John (NNP)))  
((I (PRP)) (believe (VBP)) (sincerely (RB)) (John (NNP)))  
((I (PRP)) (wanted (VBD)) (John (NNP)) (to (TO)) (leave (VB)))  
((I (PRP)) (persuaded (VBD)) (John (NNP)) (to (TO)) (leave (VB)))  
((I (PRP)) (wanted (VBD)) (it (PRP)) (to (TO)) (rain (VB)))  
((I (PRP)) (persuaded (VBD)) (it (PRP)) (to (TO)) (rain (VB)))  
((I (PRP)) (wanted (VBD)) (the (DT)) (bus (NN)) (to (TO)) (arrive (VB)) (on (IN)) (time (NN)))  
((I (PRP)) (persuaded (VBD)) (the (DT)) (bus (NN)) (to (TO)) (arrive (VB)) (on (IN)) (time (NN)))  
((I (PRP)) (persuaded (VBD)) (John (NNP)) (that (IN)) (he (PRP)) (should (MD)) (leave (VB)))  
((I (PRP)) (tried (VBD)) (to (TO)) (leave (VB)))  
((I (PRP)) (tried (VBD)) (John (NNP)) (to (TO)) (leave (VB)))  
((I (PRP)) (tried (VBD)) (it (PRP)) (to (TO)) (leave (VB)))  
((I (PRP)) (tried (VBD)) (the (DT)) (bus (NN)) (to (TO)) (leave (VB)))  
((I (PRP)) (believe (VBP)) (John (NNP)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (believe (VBP)) (that (DT)) (John (NNP)) (is (VBZ)) (here (RB)))  
((I (PRP)) (believe (VBP)) (John (NNP)) (to (TO)) (be (VB)) (a (DT)) (pathological (JJ)) (liar (NN)))  
((I (PRP)) (want (VBP)) (to (TO)) (be (VB)) (clever (NN)))  
((I (PRP)) (believe (VBP)) (to (TO)) (be (VB)) (clever (NN)))  
((John (NNP)) (was (VBD)) (persuaded (VBN)) (to (TO)) (leave (VB)))  
((John (NNP)) (was (VBD)) (believed (VBN)) (to (TO)) (be (VB)) (clever (NN)))  
((John (NNP)) (was (VBD)) (wanted (VBD)) (to (TO)) (leave (VB)))  
((John (NNP)) (is (VBZ)) (likely (JJ)) (to (TO)) (park (VB)) (here (RB)))  
((John (NNP)) (is (VBZ)) (illegal (JJ)) (to (TO)) (park (VB)) (here (RB)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (for (IN)) (John (NNP)) (to (TO)) (park (VB)) (here (RB)))  
((It (PRP)) (is (VBZ)) (illegal (JJ)) (for (IN)) (John (NNP)) (to (TO)) (park (VB)) (here (RB)))  
((I (PRP)) (believe (VBP)) (for (IN)) (John (NNP)) (to (TO)) (be (VB)) (here (RB)))  
((John (NNP)) (is (VBZ)) (believed (VBN)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (want (VBP)) (for (IN)) (John (NNP)) (to (TO)) (be (VB)) (here (RB)))  
((John (NNP)) (is (VBZ)) (wanted (VBD)) (to (TO)) (be (VB)) (here (RB)))  
((John (NNP)) (was (VBD)) (tried (VBN)) (to (TO)) (win (VB)) (the (DT)) (race (NN)))  
((John (NNP)) (is (VBZ)) (likely (JJ)) (to (TO)) (win (VB)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (that (IN)) (John (NNP)) (will (MD)) (win (VB)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (John (NNP)) (to (TO)) (win (VB)))  
((John (NNP)) (was (VBD)) (arrested (VBN)))  
((They (PRP)) (arrested (VBD)))  
((It (PRP)) (was (VBD)) (arrested (VBN)) (John (NNP)))  
((They (PRP)) (arrested (VBD)) (John (NNP)))  
((It (PRP)) (arrested (VBD)) (John (NNP)))  
((John (NNP)) (was (VBD)) (arrested (VBN)) (by (IN)) (the (DT)) (police (NN)))  
((I (PRP)) (believe (VBP)) (John (NNP)) (to (TO)) (be (VB)) (intelligent (JJ)))  
((It (PRP)) (was (VBD)) (believed (VBN)) (John (NNP)) (to (TO)) (be (VB)) (intelligent (JJ)))  
((John (NNP)) (was (VBD)) (believed (VBN)) (to (TO)) (be (VB)) (intelligent (JJ)))  
((It (PRP)) (is (VBZ)) (believed (VBN)) (by (IN)) (everyone (NN)) (that (IN)) (John (NNP)) (is (VBZ)) (intelligent (JJ)))  
((That (DT)) (John (NNP)) (is (VBZ)) (intelligent (JJ)) (is (VBZ)) (believed (VBN)) (by (IN)) (everyone (NN)))  
((I (PRP)) (am (VBP)) (proud (JJ)) (John (NNP)))  
((I (PRP)) (am (VBP)) (proud (JJ)) (of (IN)) (John (NNP)))  
((I (PRP)) (am (VBP)) (proud (JJ)) (that (IN)) (John (NNP)) (is (VBZ)) (here (RB)))  
((I (PRP)) (wonder (NN)) (who (WP)) (you (PRP)) (will (MD)) (see (VB)))  
((I (PRP)) (wonder (VBP)) (you (PRP)) (will (MD)) (see (VB)) (who (WP)))  
((Bill (NNP)) (wonders (NNS)) (who (WP)) (saw (VBP)) (Mary (NNP)))  
((Bill (NNP)) (wonders (NNS)) (who (WP)) (saw (VBP)) (what (WP)))  
((What (WP)) (does (VBZ)) (Bill (NNP)) (wonder (NN)) (who (WP)) (saw (NN)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (mention (VBP)) (Bill (NNP)) ('s (POS)) (belief (NN)) (that (IN)) (you (PRP)) (saw (VBP)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (mention (VBP)) (that (IN)) (Bill (NNP)) (believes (VBZ)) (that (IN)) (you (PRP)) (saw (VBP)))  
((I (PRP)) (wonder (VBP)) (you (PRP)) (think (VBP)) (John (NNP)) (said (VBD)) (you (PRP)) (will (MD)) (see (VB)) (who (WP)))  
((I (PRP)) (wonder (VBP)) (you (PRP)) (think (VBP)) (John (NNP)) (said (VBD)) (who (WP)) (you (PRP)) (will (MD)) (see (VB)))  
((I (PRP)) (wonder (VBP)) (you (PRP)) (think (VBP)) (who (WP)) (John (NNP)) (said (VBD)) (you (PRP)) (will (MD)) (see (VB)))  
((I (PRP)) (wonder (NN)) (who (WP)) (you (PRP)) (think (VBP)) (John (NNP)) (said (VBD)) (you (PRP)) (will (MD)) (see (VB)))  
((Bill (NNP)) (wonders (NNS)) (what (WP)) (who (WP)) (saw (NN)))  
((Bill (NNP)) (will (MD)) (solve (VB)) (which (WDT)) (problem (NN)))  
((Which (NNP)) (problem (NN)) (will (MD)) (Bill (VB)) (solve (RB)))  
((The (DT)) (problem (NN)) (was (VBD)) (solved (VBN)))  
((It (PRP)) (is (VBZ)) (raining (VBG)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (to (TO)) (be (VB)) (raining (VBG)))  
((Is (NNP)) (raining (NN)))  
((Is (RB)) (likely (JJ)) (that (IN)) (John (NNP)) (is (VBZ)) (here (RB)))  
((I (PRP)) (tried (VBD)) (to (TO)) (be (VB)) (raining (VBG)))  
((I (PRP)) (tried (VBD)) (to (TO)) (be (VB)) (likely (JJ)) (that (IN)) (John (NNP)) (is (VBZ)) (here (RB)))  
((John (NNP)) (likes (VBZ)) (him (PRP)))  
((John (NNP)) (likes (VBZ)) (himself (PRP)))  
((John (NNP)) (believes (VBZ)) (that (DT)) (Mary (NNP)) (likes (VBZ)) (him (PRP)))  
((John (NNP)) (believes (VBZ)) (that (DT)) (Mary (NNP)) (likes (VBZ)) (himself (PRP)))  
((John (NNP)) ('s (POS)) (mother (NN)) (likes (NNS)) (himself (PRP)))  
((John (NNP)) ('s (POS)) (picture (NN)) (of (IN)) (himself (PRP)) (is (VBZ)) (nice (RB)))  
((John (NNP)) ('s (POS)) (mother (NN)) (likes (NNS)) (him (PRP)))  
((John (NNP)) ('s (POS)) (picture (NN)) (of (IN)) (him (PRP)) (is (VBZ)) (nice (RB)))  
((Himself (PRP)) (likes (VBZ)) (John (NNP)))  
((They (PRP)) (like (IN)) (each (DT)) (other (JJ)))  
((Their (PRP$)) (pictures (NNS)) (of (IN)) (each (DT)) (other (JJ)) (are (VBP)) (nice (RB)))  
((They (PRP)) (believe (VBP)) (Mary (NNP)) (likes (NNS)) (each (DT)) (other (JJ)))  
((Their (RB)) (mothers (NNS)) (like (IN)) (each (DT)) (other (JJ)))  
((Each (NNP)) (other (JJ)) (like (VB)) (them (PRP)))  
((John (NNP)) (believes (VBZ)) (himself (PRP)) (to (TO)) (like (VB)) (Mary (NNP)))  
((John (NNP)) (believes (VBZ)) (him (PRP)) (to (TO)) (like (VB)) (Mary (NNP)))  
((John (NNP)) (believes (VBZ)) (that (DT)) (himself (PRP)) (likes (VBZ)) (Mary (NNP)))  
((John (NNP)) (believes (VBZ)) (that (IN)) (he (PRP)) (likes (VBZ)) (Mary (NNP)))  
((John (NNP)) (believes (VBZ)) (Mary (NNP)) (to (TO)) (like (VB)) (himself (PRP)))  
((John (NNP)) (believes (VBZ)) (Mary (NNP)) (to (TO)) (like (VB)) (him (PRP)))  
((John (NNP)) (likes (VBZ)) (Mary (NNP)) ('s (POS)) (pictures (NNS)) (of (IN)) (him (PRP)))  
((John (NNP)) (likes (VBZ)) (Mary (NNP)) ('s (POS)) (pictures (NNS)) (of (IN)) (himself (PRP)))  
((John (NNP)) (likes (VBZ)) (pictures (NNS)) (of (IN)) (himself (PRP)))  
((John (NNP)) (saw (NNP)) (pictures (NNS)) (of (IN)) (himself (PRP)))  
((John (NNP)) (saw (NNP)) (pictures (NNS)) (of (IN)) (him (PRP)))  
((They (PRP)) (read (VB)) (their (PRP$)) (books (NNS)))  
((They (PRP)) (read (VB)) (each (DT)) (other (JJ)) ('s (POS)) (books (NNS)))  
((They (PRP)) (read (VB)) (themselves (NNS)) (' (POS)) (books (NNS)))  
((John (NNP)) (likes (VBZ)) (John (NNP)))  
((John (NNP)) (thinks (VBZ)) (John (NNP)) (likes (NNS)) (Mary (NNP)))  
((John (NNP)) (thinks (VBZ)) (he (PRP)) (likes (VBZ)) (Mary (NNP)))  
((John (NNP)) (thinks (VBZ)) (Mary (NNP)) (likes (NNS)) (John (NNP)))  
((John (NNP)) (thinks (VBZ)) (Mary (NNP)) (likes (NNS)) (him (PRP)))  
((John (NNP)) (ca (MD)) (n't (RB)) (stand (VB)) (John (NNP)) ('s (POS)) (teacher (NN)))  
((John (NNP)) ('s (POS)) (teacher (NN)) (ca (MD)) (n't (RB)) (stand (VB)) (John (NNP)))  
((John (NNP)) (ca (MD)) (n't (RB)) (stand (VB)) (the (DT)) (bastard (NN)) ('s (POS)) (teacher (NN)))  
((John (NNP)) ('s (POS)) (teacher (NN)) (ca (MD)) (n't (RB)) (stand (VB)) (the (DT)) (bastard (NN)))  
((John (NNP)) (thinks (VBZ)) (the (DT)) (bastard (NN)) (likes (VBZ)) (Mary (NNP)))  
((John (NNP)) (thinks (VBZ)) (Mary (NNP)) (likes (VBZ)) (the (DT)) (bastard (NN)))  
((He (PRP)) (likes (VBZ)) (John (NNP)))  
((He (PRP)) (thinks (VBZ)) (John (NNP)) (likes (NNS)) (Mary (NNP)))  
((He (PRP)) (thinks (VBZ)) (Mary (NNP)) (likes (NNS)) (John (NNP)))  
((He (PRP)) (ca (MD)) (n't (RB)) (stand (VB)) (John (NNP)) ('s (POS)) (teacher (NN)))  
((Who (NNP)) (thinks (VBZ)) (Mary (NNP)) (likes (NNS)) (him (PRP)))  
((Who (NNP)) (does (VBZ)) (he (PRP)) (think (VB)) (Mary (NNP)) (likes (NNS)))  
((Who (NNP)) (left (VBD)))  
((John (NNP)) (believes (VBZ)) (that (DT)) (himself (PRP)) (is (VBZ)) (clever (RB)))  
((John (NNP)) (was (VBD)) (believed (VBN)) (that (IN)) (is (VBZ)) (clever (RB)))  
((John (NNP)) (believes (VBZ)) (himself (PRP)) (to (TO)) (be (VB)) (clever (NN)))  
((John (NNP)) (was (VBD)) (believed (VBN)) (to (TO)) (be (VB)) (clever (NN)))  
((He (PRP)) (likes (VBZ)) (him (PRP)))  
((John (NNP)) (left (VBD)))  
((John (NNP)) (likes (VBZ)) (himself (PRP)))  
((We (PRP)) (like (IN)) (me (PRP)))  
((We (PRP)) (think (VBP)) (that (IN)) (I (PRP)) (will (MD)) (win (VB)))  
((We (PRP)) (like (IN)) (myself (PRP)))  
((They (PRP)) (like (IN)) (themselves (NNS)))  
((John (NNP)) (told (VBD)) (Bill (NNP)) (that (IN)) (they (PRP)) (should (MD)) (leave (VB)))  
((I (PRP)) (want (VBP)) (to (TO)) (visit (VB)) (you (PRP)))  
((They (PRP)) (want (VBP)) (to (TO)) (visit (VB)) (each (DT)) (other (JJ)))  
((I (PRP)) (tried (VBD)) (to (TO)) (understand (VB)) (the (DT)) (problem (NN)))  
((It (PRP)) (is (VBZ)) (important (JJ)) (to (TO)) (understand (VB)) (the (DT)) (problem (NN)))  
((Eats (NNS)))  
((It (PRP)) (is (VBZ)) (important (JJ)) (to (TO)) (eat (NN)))  
((Was (NNP)) (arrested (VBD)))  
((It (PRP)) (was (VBD)) (arrested (VBN)))  
((There (EX)) (was (VBD)) (arrested (VBN)))  
((I (PRP)) (believe (VBP)) (to (TO)) (be (VB)) (here (RB)))  
((I (PRP)) (want (VBP)) (John (NNP)) (to (TO)) (win (VB)))  
((I (PRP)) (want (VBP)) (to (TO)) (win (VB)))  
((I (PRP)) (tried (VBD)) (to (TO)) (win (VB)))  
((I (PRP)) (tried (VBD)) (John (NNP)) (to (TO)) (win (VB)))  
((I (PRP)) (believe (VBP)) (John (NNP)) (to (TO)) (have (VB)) (won (VBN)))  
((I (PRP)) (believe (VBP)) (to (TO)) (have (VB)) (won (VBN)))  
((I (PRP)) (saw (NNP)) (John (NNP)) ('s (POS)) (destruction (NN)) (of (IN)) (the (DT)) (building (NN)))  
((I (PRP)) (saw (NNP)) (John (NNP)) ('s (POS)) (destruction (NN)) (the (DT)) (building (NN)))  
((I (PRP)) (saw (NNP)) (John (NNP)) ('s (POS)) (destruction (NN)))  
((I (PRP)) (am (VBP)) (proud (JJ)))  
((I (PRP)) (am (VBP)) (proud (JJ)) (of (IN)) (my (PRP$)) (belief (NN)) (to (TO)) (be (VB)) (intelligent (JJ)))  
((The (DT)) (men (NNS)) (think (VBP)) (that (DT)) (pictures (NNS)) (of (IN)) (each (DT)) (other (JJ)) (will (MD)) (be (VB)) (on (IN)) (sale (NN)))  
((They (PRP)) (liked (VBD)) (Mary (NNP)) ('s (POS)) (pictures (NNS)) (of (IN)) (each (DT)) (other (JJ)))  
((They (PRP)) (like (IN)) (each (DT)) (other (JJ)) ('s (POS)) (books (NNS)))  
((They (PRP)) (think (VBP)) (that (IN)) (each (DT)) (other (JJ)) (are (VBP)) (intelligent (JJ)))  
((Each (NNP)) (other (JJ)) (left (VBD)))  
((Left (NNP)))  
((The (DT)) (men (NNS)) (think (VBP)) (that (IN)) (Mary (NNP)) ('s (POS)) (pictures (NNS)) (of (IN)) (each (DT)) (other (JJ)) (will (MD)) (be (VB)) (on (IN)) (sale (NN)))  
((The (DT)) (men (NNS)) (think (VBP)) (that (IN)) (I (PRP)) (like (IN)) (pictures (NNS)) (of (IN)) (each (DT)) (other (JJ)))  
((They (PRP)) (think (VBP)) (that (IN)) (it (PRP)) (is (VBZ)) (likely (JJ)) (that (IN)) (pictures (NNS)) (of (IN)) (each (DT)) (other (JJ)) (are (VBP)) (on (IN)) (sale (NN)))  
((That (DT)) (John (NNP)) (is (VBZ)) (here (RB)) (is (VBZ)) (likely (JJ)))  
((They (PRP)) (think (VBP)) (that (IN)) (it (PRP)) (surprised (VBD)) (each (DT)) (other (JJ)) (that (IN)) (Bill (NNP)) (won (NNP)))  
((John (NNP)) (is (VBZ)) (likely (JJ)) (to (TO)) (leave (VB)))  
((John (NNP)) (seems (VBZ)) (that (IN)) (it (PRP)) (is (VBZ)) (likely (JJ)) (to (TO)) (leave (VB)))  
((Pictures (NNS)) (of (IN)) (each (DT)) (other (JJ)) (are (VBP)) (on (IN)) (sale (NN)))  
((Pictures (NNS)) (of (IN)) (are (VBP)) (on (IN)) (sale (NN)))  
((The (DT)) (men (NNS)) (think (VBP)) (that (DT)) (pictures (NNS)) (of (IN)) (them (PRP)) (are (VBP)) (on (IN)) (sale (NN)))  
((John (NNP)) (said (VBD)) (that (IN)) (his (PRP$)) (brother (NN)) (likes (VBZ)) (himself (PRP)))  
((We (PRP)) (believed (VBD)) (Mary (NNP)) (to (TO)) (like (VB)) (each (DT)) (other (JJ)))  
((He (PRP)) (thinks (VBZ)) (Mary (NNP)) (likes (NNS)) (John (NNP)))  
((Who (NNP)) (does (VBZ)) (he (PRP)) (like (VB)))  
((Who (NNP)) (was (VBD)) (arrested (VBN)))  
((John (NNP)) (tried (VBD)) (to (TO)) (win (VB)) (the (DT)) (race (NN)))  
((John (NNP)) (seems (VBZ)) (to (TO)) (be (VB)) (crazy (NN)))  
((John (NNP)) (was (VBD)) (arrested (VBN)) (after (IN)) (leading (VBG)) (the (DT)) (demonstration (NN)))  
((John (NNP)) (is (VBZ)) (too (RB)) (dumb (JJ)) (to (TO)) (talk (VB)) (to (TO)))  
((Who (NN)) (did (VBD)) (he (PRP)) (try (VB)) (to (TO)) (win (VB)) (the (DT)) (race (NN)))  
((Which (NNP)) (report (NN)) (did (VBD)) (you (PRP)) (file (VBP)) (without (IN)) (reading (NN)))  
((Which (NNP)) (book (NN)) (did (VBD)) (you (PRP)) (file (VBP)) (the (DT)) (report (NN)) (without (IN)) (reading (VBG)))  
((Who (NNP)) (filed (VBN)) (which (WDT)) (report (NN)) (without (IN)) (reading (VBG)))  
((The (DT)) (report (NN)) (was (VBD)) (filed (VBN)) (without (IN)) (reading (NN)))  
((The (DT)) (report (NN)) (fell (VBD)) (on (IN)) (the (DT)) (floor (NN)) (after (IN)) (reading (VBG)) (the (DT)) (book (NN)))  
((The (DT)) (teacher (NN)) (fell (VBD)) (on (IN)) (the (DT)) (floor (NN)) (after (IN)) (reading (VBG)) (the (DT)) (book (NN)))  
((Which (NNP)) (report (NN)) (did (VBD)) (you (PRP)) (file (VBP)) (after (IN)) (you (PRP)) (read (VB)))  
((The (DT)) (report (NN)) (was (VBD)) (filed (VBN)) (after (IN)) (Bill (NNP)) (read (VB)))  
((What (WP)) (was (VBD)) (filed (VBN)) (without (IN)) (being (VBG)) (read (VB)))  
((The (DT)) (report (NN)) (was (VBD)) (filed (VBN)) (without (IN)) (being (VBG)) (read (VB)))  
((The (DT)) (report (NN)) (disappeared (VBD)) (without (IN)) (being (VBG)) (read (VB)))  
((The (DT)) (teacher (NN)) (was (VBD)) (fired (VBN)) (without (IN)) (talking (VBG)) (to (TO)))  
((The (DT)) (teacher (NN)) (was (VBD)) (fired (VBN)) (after (IN)) (he (PRP)) (talked (VBD)) (to (TO)))  
((The (DT)) (teacher (NN)) (resigned (VBD)) (after (IN)) (talking (VBG)) (to (TO)))  
((Who (NNP)) (resigned (VBD)) (before (IN)) (we (PRP)) (could (MD)) (fire (VB)))  
((Who (NNP)) (resigned (VBD)) (before (IN)) (we (PRP)) (could (MD)) (fire (VB)) (him (PRP)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (hire (VBP)) (because (IN)) (Mary (NNP)) (said (VBD)) (would (MD)) (work (VB)) (hard (RB)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (hire (VBP)) (because (IN)) (he (PRP)) (said (VBD)) (would (MD)) (work (VB)) (hard (RB)))  
((The (DT)) (report (NN)) (which (WDT)) (I (PRP)) (filed (VBN)) (without (IN)) (reading (VBG)) (disappeared (VBD)))  
((The (DT)) (man (NN)) (who (WP)) (I (PRP)) (hired (VBD)) (because (RB)) (Mary (NNP)) (said (VBD)) (would (MD)) (work (VB)) (hard (JJ)) (disappeared (VBD)))  
((The (DT)) (man (NN)) (who (WP)) (I (PRP)) (hired (VBD)) (because (IN)) (he (PRP)) (said (VBD)) (would (MD)) (work (VB)) (hard (JJ)) (disappeared (VBD)))  
((This (DT)) (article (NN)) (is (VBZ)) (too (RB)) (illogical (JJ)) (to (TO)) (read (VB)) (without (IN)) (laughing (NN)) (at (IN)))  
((Who (NNP)) (left (VBD)) (after (IN)) (you (PRP)) (insulted (VBD)))  
((Who (NNP)) (left (VBD)) (after (IN)) (you (PRP)) (insulted (VBD)) (him (PRP)))  
((The (DT)) (article (NN)) (which (WDT)) (I (PRP)) (filed (VBN)) (it (PRP)) (yesterday (NN)) (without (IN)) (reading (VBG)) (is (VBZ)) (over (IN)) (here (RB)))  
((What (WP)) (did (VBD)) (you (PRP)) (meet (VB)) (a (DT)) (man (NN)) (who (WP)) (likes (VBZ)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (give (VBP)) (a (DT)) (picture (NN)) (of (IN)) (to (TO)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (give (VBP)) (a (DT)) (picture (NN)) (of (IN)) (to (TO)) (Bill (NNP)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (give (VBP)) (a (DT)) (picture (NN)) (of (IN)) (Bill (NNP)) (to (TO)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (give (VBP)) (a (DT)) (picture (NN)) (of (IN)) (who (WP)) (to (TO)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (put (VB)) (a (DT)) (picture (NN)) (of (IN)) (under (IN)))  
((John (NNP)) (was (VBD)) (hired (VBN)))  
((Died (NNP)))  
((John (NNP)) (was (VBD)) (killed (VBN)))  
((Who (NNP)) (was (VBD)) (killed (VBN)))  
((John (NNP)) (wanted (VBD)) (to (TO)) (be (VB)) (arrested (VBN)))  
((John (NNP)) (tried (VBD)) (to (TO)) (win (VB)))  
((Who (NNP)) (is (VBZ)) (it (PRP)) (likely (JJ)) (to (TO)) (win (VB)) (the (DT)) (race (NN)))  
((Who (NNP)) (is (VBZ)) (it (PRP)) (likely (JJ)) (will (MD)) (win (VB)) (the (DT)) (race (NN)))  
((The (DT)) (man (NN)) (that (IN)) (I (PRP)) (wonder (VBP)) (whether (IN)) (he (PRP)) (will (MD)) (win (VB)) (the (DT)) (race (NN)) (disappeared (VBD)))  
((The (DT)) (man (NN)) (who (WP)) (I (PRP)) (wonder (NN)) (whether (IN)) (he (PRP)) (will (MD)) (win (VB)) (the (DT)) (race (NN)) (disappeared (VBD)))  
((The (DT)) (man (NN)) (who (WP)) (you (PRP)) (wonder (NN)) (whether (IN)) (he (PRP)) (will (MD)) (win (VB)) (the (DT)) (race (NN)) (disappeared (VBD)))  
((Which (NNP)) (man (NN)) (do (VBP)) (you (PRP)) (wonder (VB)) (whether (IN)) (he (PRP)) (will (MD)) (win (VB)) (the (DT)) (race (NN)))  
((It (PRP)) (is (VBZ)) (crucial (JJ)) (john (NN)) (to (TO)) (see (VB)) (this (DT)))  
((John (NNP)) (is (VBZ)) (crucial (JJ)) (to (TO)) (see (VB)) (this (DT)))  
((John (NNP)) (is (VBZ)) (certain (JJ)) (to (TO)) (see (VB)) (this (DT)))  
((It (PRP)) (is (VBZ)) (certain (JJ)) (to (TO)) (see (VB)) (this (DT)))  
((Who (PRP)) (do (VBP)) (you (PRP)) (think (VBP)) (that (IN)) (John (NNP)) (saw (NNP)))  
((Who (PRP)) (do (VBP)) (you (PRP)) (think (VB)) (John (NNP)) (saw (NNP)))  
((Who (PRP)) (do (VBP)) (you (PRP)) (think (VBP)) (that (IN)) (saw (NN)) (Bill (NNP)))  
((Who (PRP)) (do (VBP)) (you (PRP)) (think (VBP)) (saw (JJ)) (Bill (NNP)))  
((Who (NNP)) (did (VBD)) (you (PRP)) (say (VBP)) (that (IN)) (John (NNP)) (likes (NNS)))  
((John (NNP)) (is (VBZ)) (believed (VBN)) (is (VBZ)) (intelligent (JJ)))  
((John (NNP)) (seems (VBZ)) (that (IN)) (it (PRP)) (is (VBZ)) (likely (JJ)) (to (TO)) (leave (VB)))  
((Who (NNP)) (will (MD)) (read (VB)) (what (WP)))  
((What (WP)) (will (MD)) (who (WP)) (read (VB)))  
((You (PRP)) (will (MD)) (read (VB)) (what (WP)))  
((What (WP)) (will (MD)) (you (PRP)) (read (VB)))  
((I (PRP)) (wonder (VBP)) (you (PRP)) (will (MD)) (read (VB)) (what (WP)))  
((I (PRP)) (wonder (VBP)) (you (PRP)) (will (MD)) (read (VB)) (the (DT)) (book (NN)))  
((Why (NNP)) (did (VBD)) (you (PRP)) (read (VB)) (what (WP)))  
((What (WP)) (did (VBD)) (you (PRP)) (read (VB)) (why (JJ)))  
((Who (NNP)) (left (VBD)) (why (JJ)))  
((Why (NNP)) (did (VBD)) (who (WP)) (leave (VBP)))  
((Who (NNP)) (believes (VBZ)) (the (DT)) (claim (NN)) (that (WDT)) (Mary (NNP)) (read (VB)) (what (WP)))  
((What (WP)) (do (VBP)) (you (PRP)) (believe (VBP)) (the (DT)) (claim (NN)) (that (WDT)) (Mary (NNP)) (read (VB)))  
((Who (NNP)) (believes (VBZ)) (the (DT)) (claim (NN)) (that (IN)) (John (NNP)) (hit (NNP)) (who (WP)))  
((Who (NNP)) (believes (VBZ)) (the (DT)) (claim (NN)) (that (IN)) (John (NNP)) (left (VBD)) (why (JJ)))  
((Who (NNP)) (does (VBZ)) (Mary (NNP)) (believe (VB)) (the (DT)) (claim (NN)) (that (IN)) (John (NNP)) (hit (NNP)))  
((Why (NNP)) (does (VBZ)) (Mary (NNP)) (believe (VB)) (the (DT)) (claim (NN)) (that (IN)) (John (NNP)) (left (VBD)))  
((Who (NNP)) (does (VBZ)) (Mary (NNP)) (wonder (VB)) (why (JJ)) (John (NNP)) (hit (NN)))  
((Why (NNP)) (does (VBZ)) (Mary (NNP)) (wonder (NN)) (who (WP)) (John (NNP)) (hit (NN)))  
((Why (RB)) (do (VBP)) (you (PRP)) (think (VBP)) (that (IN)) (John (NNP)) (left (VBD)))  
((Who (PRP)) (do (VBP)) (you (PRP)) (think (VBP)) (that (DT)) (Mary (NNP)) (said (VBD)) (won (IN)) (the (DT)) (race (NN)))  
((Who (PRP)) (do (VBP)) (you (PRP)) (think (VBP)) (that (IN)) (left (VBD)))  
((John (NNP)) (is (VBZ)) (likely (JJ)) (to (TO)) (be (VB)) (clever (NN)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (John (NNP)) (to (TO)) (be (VB)) (clever (NN)))  
((Mary (NNP)) (tried (VBD)) (to (TO)) (win (VB)) (the (DT)) (race (NN)))  
((Mary (NNP)) (tried (VBD)) (Bill (NNP)) (to (TO)) (win (VB)) (the (DT)) (race (NN)))  
((Who (NNP)) (is (VBZ)) (it (PRP)) (likely (JJ)) (to (TO)) (be (VB)) (clever (NN)))  
((The (DT)) (man (NN)) (that (IN)) (it (PRP)) (is (VBZ)) (likely (JJ)) (to (TO)) (be (VB)) (clever (JJR)) (disappeared (VBD)))  
((The (DT)) (man (NN)) (that (IN)) (it (PRP)) (is (VBZ)) (likely (JJ)) (is (VBZ)) (clever (NN)) (disappeared (VBD)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (it (PRP)) (to (TO)) (rain (VB)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (there (RB)) (to (TO)) (be (VB)) (a (DT)) (man (NN)) (here (RB)))  
((I (PRP)) (tried (VBD)) (it (PRP)) (to (TO)) (seem (VBP)) (that (IN)) (Bill (NNP)) (was (VBD)) (intelligent (VBN)))  
((It (PRP)) (is (VBZ)) (likely (JJ)) (it (PRP)) (to (TO)) (seem (VBP)) (that (IN)) (Bill (NNP)) (is (VBZ)) (intelligent (JJ)))  
((It (PRP)) (often (RB)) (rains (VBZ)) (without (IN)) (snowing (VBG)))  
((John (NNP)) (is (VBZ)) (likely (JJ)) (to (TO)) (be (VB)) (intelligent (JJ)))  
((I (PRP)) (am (VBP)) (proud (JJ)) (that (IN)) (John (NNP)) (won (VBD)) (the (DT)) (race (NN)))  
((John (NNP)) (is (VBZ)) (tough (JJ)) (to (TO)) (please (VB)))  
((It (PRP)) (is (VBZ)) (tough (JJ)) (to (TO)) (please (VB)) (John (NNP)))  
((John (NNP)) (is (VBZ)) (likely (JJ)) (to (TO)) (win (VB)) (the (DT)) (race (NN)))  
((Who (PRP)) (does (VBZ)) (his (PRP$)) (mother (NN)) (love (NN)))  
((His (PRP$)) (mother (NN)) (loves (VBZ)) (everyone (NN)))  
((Every (RB)) (man (NN)) (likes (NNS)) (some (DT)) (symphony (NN)) (he (PRP)) (heard (NN)))  
((Every (RB)) (man (NN)) (asked (VBD)) (some (DT)) (actress (NN)) (that (IN)) (he (PRP)) (met (VBZ)) (about (IN)) (some (DT)) (play (VB)) (that (WDT)) (she (PRP)) (appeared (VBN)) (in (RP)))  
((Someone (NN)) (gave (VBD)) (every (JJ)) (actress (NN)) (that (IN)) (he (PRP)) (met (VBZ)) (a (DT)) (book (NN)) (that (WDT)) (she (PRP)) (appreciated (VBD)))  
((Which (NNP)) (man (NN)) (liked (VBD)) (which (WDT)) (symphony (VBP)) (he (PRP)) (heard (NN)))  
((John (NNP)) (seems (VBZ)) (that (IN)) (he (PRP)) (likes (VBZ)))  
((John (NNP)) (asked (VBD)) (Mary (NNP)) (about (IN)) (themselves (NNS)))  
((We (PRP)) (like (IN)) (myself (PRP)))  
((John (NNP)) (seems (VBZ)) (is (VBZ)) (crazy (NN)))  
((John (NNP)) (tried (VBD)) (Bill (NNP)) (to (TO)) (seem (VBP)) (that (IN)) (he (PRP)) (likes (VBZ)))  
((John (NNP)) (tried (VBD)) (to (TO)) (be (VB)) (arrested (VBN)))  
((Mary (NNP)) (is (VBZ)) (proud (VBN)) (of (IN)) (Bill (NNP)))  
((John (NNP)) (seems (VBZ)) (that (IN)) (he (PRP)) (is (VBZ)) (proud (RB)))  
((The (DT)) (destruction (NN)) (Rome (NNP)) (worked (VBD)))  
((The (DT)) (destruction (NN)) (of (IN)) (Rome (NNP)) (worked (VBD)))  
((The (DT)) (belief (NN)) (John (NNP)) (to (TO)) (be (VB)) (clever (NN)) (is (VBZ)) (illogical (JJ)))  
((The (DT)) (belief (NN)) (of (IN)) (John (NNP)) (to (TO)) (be (VB)) (clever (NN)) (is (VBZ)) (illogical (JJ)))  
((The (DT)) (belief (NN)) (that (IN)) (John (NNP)) (is (VBZ)) (clever (NN)) (is (VBZ)) (illogical (JJ)))  
((John (NNP)) ('s (POS)) (belief (NN)) (to (TO)) (be (VB)) (clever (NN)) (is (VBZ)) (illogical (JJ)))  
((John (NNP)) (seems (VBZ)) (that (IN)) (his (PRP$)) (belief (NN)) (to (TO)) (be (VB)) (clever (NN)) (is (VBZ)) (ill (JJ)) (founded (VBD)))  
((John ((NNP)) (, (,)) (I (PRP)) (like (IN)))  
((John ((NNP)) (, (,)) (Mary (NNP)) (thinks (VBZ)) (I (PRP)) (like (VB)))  
((John ((NNP)) (, (,)) (he (PRP)) (thinks (VBZ)) (I (PRP)) (like (VB)))  
((John ((NNP)) (, (,)) (Mary (NNP)) (thinks (VBZ)) (that (DT)) (John (NNP)) (said (VBD)) (that (IN)) (Susan (NNP)) (believes (VBZ)) (I (PRP)) (like (VB)))  
((Syntactic (JJ)) (structures ((NNS)) (, (,)) (I (PRP)) (wonder (VBP)) (who (WP)) (read (VB)))  
((Syntactic (JJ)) (structures ((NNS)) (, (,)) (I (PRP)) (met (VBP)) (the (DT)) (man (NN)) (who (WP)) (wrote (VBD)))  
((John ((NNP)) (, (,)) (I (PRP)) (think (VBP)) (that (WDT)) (won (VBP)) (the (DT)) (race (NN)))  
((John ((NNP)) (, (,)) (I (PRP)) (think (VBP)) (won (VB)) (the (DT)) (race (NN)))  
((He (PRP)) (likes (VBZ)) (everyone (NN)) (that (IN)) (John (NNP)) (knows (VBZ)))  
((Everyone (RB)) (that (IN)) (John (NNP)) (knows (VBZ)) (he (PRP)) (likes (NNS)))  
((John (NNP)) (likes (VBZ)) (every (JJ)) (picture (NN)) (of (IN)) (himself (PRP)))  
((Every (RB)) (picture (NN)) (of (IN)) (himself (PRP)) (John (NNP)) (likes (NNS)))  